apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../k8s/
images:
- digest: sha256:f115098984d54ea36a96b4000000940309c3c18a16f967b45e34b579b00c6e82
  name: quay.io/jgoldsmith/vote-api
  newName: quay.io/jgoldsmith/vote-api
- digest: sha256:057b90c5cc35f3297af37b31a981f930542e60300dfb6eb161d23acf0db885d3
  name: quay.io/jgoldsmith/vote-ui
  newName: quay.io/jgoldsmith/vote-ui
